# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
author: AI@MBL Team
name: AI@MBL
title: Artificial Intelligence for Microscopy Image Analysis
description: >
  The goal of this course is to familiarize researchers in the life sciences with state-of-the-art deep learning techniques
  for microscopy image analysis and to introduce them to tools and frameworks that facilitate independent application of the
  learned material after the course.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
repository: ai-mbl/ai-mbl.github.io
url: https://ai-mbl.github.io # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: ai-mbl

# Optional features
show_social_icons:  true
enable_anchorjs:    true
enable_latexjs:     true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
# collections:
#   announcements:
#     defaults:
#       layout: post
#     output: true
#     permalink: /announcements/:path/

# announcements_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji
    - jekyll-toc

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"

theme: jekyll-theme-slate